### ISSUE TITLE
Which RPM are the motors ?

### ISSUE THREAD

**Issue by TomasHricina** [Yadunund/mecanum_bot#1]
Hello, I would love to reproduce your robot.
Please, what RPM are your motors ?
Thank you

**Comment by Yadunund** [comment]
Hi there!
I got the 178RPM model from [here](https://www.aliexpress.com/item/32999954820.html?spm=a2g0s.9042311.0.0.77f04c4dQrNWkg)

Have updated the README https://github.com/Yadunund/mecanum_bot/commit/a8a2e8d319abf9aeebfe1ac8650ad93dea27f1c6

**Comment by TomasHricina** [comment]
Thanks :)
